version : "3"
services:
 web:
    build: 
        context: .
        dockerfile: Dockerfile.redis
    ports:
        - "5000:5000"
    volumes:
        - .:/redisapp 
 redis :
    image : "redis:alpine"
